package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences;
import android.support.v7.widget.helper.ItemTouchHelper;
import com.facebook.appevents.AppEventsConstants;
import com.google.android.exoplayer2.ExoPlayerFactory;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
@zzzt
/* loaded from: classes.dex */
public final class zzmu {
    private static zzmk<String> zzbfu = zzmk.zza(0, "gads:sdk_core_experiment_id");
    public static final zzmk<String> zzbfv = zzmk.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static zzmk<Boolean> zzbfw = zzmk.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static zzmk<String> zzbfx = zzmk.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    private static zzmk<Boolean> zzbfy = zzmk.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static zzmk<String> zzbfz = zzmk.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzmk<Boolean> zzbga = zzmk.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbgb = zzmk.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzmk<String> zzbgc = zzmk.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzmk<Boolean> zzbgd = zzmk.zza(0, "gads:block_autoclicks", (Boolean) false);
    private static zzmk<String> zzbge = zzmk.zza(0, "gads:block_autoclicks_experiment_id");
    private static zzmk<String> zzbgf = zzmk.zza(0, "gads:spam_app_context:experiment_id");
    public static final zzmk<Boolean> zzbgg = zzmk.zza(1, "gads:spam_app_context:enabled", (Boolean) false);
    private static zzmk<Integer> zzbgh = zzmk.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzmk<String> zzbgi = zzmk.zza(1, "gads:video_exo_player:version", AppEventsConstants.EVENT_PARAM_VALUE_YES);
    private static zzmk<String> zzbgj = zzmk.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzmk<Integer> zzbgk = zzmk.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzmk<Integer> zzbgl = zzmk.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzmk<Integer> zzbgm = zzmk.zza(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final zzmk<Integer> zzbgn = zzmk.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzmk<Long> zzbgo = zzmk.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final zzmk<Long> zzbgp = zzmk.zza(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    public static final zzmk<Integer> zzbgq = zzmk.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzmk<Boolean> zzbgr = zzmk.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzmk<String> zzbgs = zzmk.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzmk<Long> zzbgt = zzmk.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final zzmk<Boolean> zzbgu = zzmk.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzmk<Long> zzbgv = zzmk.zza(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final zzmk<Boolean> zzbgw = zzmk.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzmk<Integer> zzbgx = zzmk.zza(1, "gads:video:spinner:scale", 4);
    public static final zzmk<Long> zzbgy = zzmk.zza(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final zzmk<Boolean> zzbgz = zzmk.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzmk<Boolean> zzbha = zzmk.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzmk<Boolean> zzbhb = zzmk.zza(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final zzmk<String> zzbhc = zzmk.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzmk<Integer> zzbhd = zzmk.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static zzmk<Boolean> zzbhe = zzmk.zza(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static zzmk<Float> zzbhf = zzmk.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static zzmk<String> zzbhg = zzmk.zza(0, "gads:ad_id_app_context:experiment_id");
    private static zzmk<String> zzbhh = zzmk.zza(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static zzmk<Boolean> zzbhi = zzmk.zza(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static zzmk<Float> zzbhj = zzmk.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static zzmk<String> zzbhk = zzmk.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzmk<Boolean> zzbhl = zzmk.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbhm = zzmk.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    private static zzmk<Boolean> zzbhn = zzmk.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzmk<String> zzbho = zzmk.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzmk<String> zzbhp = zzmk.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzmk<String> zzbhq = zzmk.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzmk<Boolean> zzbhr = zzmk.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzmk<String> zzbhs = zzmk.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzmk<Boolean> zzbht = zzmk.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzmk<Boolean> zzbhu = zzmk.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzmk<Integer> zzbhv = zzmk.zza(0, "gads:content_length_weight", 1);
    public static final zzmk<Integer> zzbhw = zzmk.zza(0, "gads:content_age_weight", 1);
    public static final zzmk<Integer> zzbhx = zzmk.zza(0, "gads:min_content_len", 11);
    public static final zzmk<Integer> zzbhy = zzmk.zza(0, "gads:fingerprint_number", 10);
    public static final zzmk<Integer> zzbhz = zzmk.zza(0, "gads:sleep_sec", 10);
    public static final zzmk<Boolean> zzbia = zzmk.zza(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final zzmk<Integer> zzbib = zzmk.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzmk<Boolean> zzbic = zzmk.zza(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final zzmk<Integer> zzbid = zzmk.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzmk<Integer> zzbie = zzmk.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzmk<String> zzbif = zzmk.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzmk<String> zzbig = zzmk.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzmk<Boolean> zzbih = zzmk.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbii = zzmk.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzmk<Boolean> zzbij = zzmk.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzmk<Long> zzbik = zzmk.zza(0, "gads:app_index:timeout_ms", 1000L);
    private static zzmk<String> zzbil = zzmk.zza(0, "gads:app_index:experiment_id");
    private static zzmk<String> zzbim = zzmk.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzmk<Boolean> zzbin = zzmk.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbio = zzmk.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzmk<Boolean> zzbip = zzmk.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    private static zzmk<String> zzbiq = zzmk.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static zzmk<Boolean> zzbir = zzmk.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbis = zzmk.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbit = zzmk.zza(1, "gads:sai:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbiu = zzmk.zza(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbiv = zzmk.zza(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbiw = zzmk.zza(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbix = zzmk.zza(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final zzmk<String> zzbiy = zzmk.zza(1, "gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
    public static final zzmk<String> zzbiz = zzmk.zza(1, "gads:sai:impression_ping_schema", "[\"/adview\"]");
    public static final zzmk<Boolean> zzbja = zzmk.zza(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbjb = zzmk.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzmk<String> zzbjc = zzmk.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzmk<Long> zzbjd = zzmk.zza(1, "gads:sai:timeout_ms", 100L);
    public static final zzmk<Integer> zzbje = zzmk.zza(1, "gads:sai:scion_thread_pool_size", 5);
    private static zzmk<Integer> zzbjf = zzmk.zza(0, "gads:webview_cache_version", 0);
    public static final zzmk<Boolean> zzbjg = zzmk.zza(1, "gads:webview_recycle:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbjh = zzmk.zza(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    private static zzmk<String> zzbji = zzmk.zzb(0, "gads:pan:experiment_id");
    public static final zzmk<Boolean> zzbjj = zzmk.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final zzmk<Long> zzbjk = zzmk.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final zzmk<Boolean> zzbjl = zzmk.zza(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final zzmk<Long> zzbjm = zzmk.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final zzmk<Long> zzbjn = zzmk.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzmk<Boolean> zzbjo = zzmk.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzmk<Long> zzbjp = zzmk.zza(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    public static final zzmk<Boolean> zzbjq = zzmk.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzmk<Boolean> zzbjr = zzmk.zza(1, "gads:enable_ad_loader_manager", (Boolean) true);
    private static zzmk<Boolean> zzbjs = zzmk.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbjt = zzmk.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) false);
    public static final zzmk<Long> zzbju = zzmk.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) ExoPlayerFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzmk<Boolean> zzbjv = zzmk.zza(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    private static zzmk<Boolean> zzbjw = zzmk.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static zzmk<String> zzbjx = zzmk.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static zzmk<Integer> zzbjy = zzmk.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static zzmk<Integer> zzbjz = zzmk.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzmk<Boolean> zzbka = zzmk.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbkb = zzmk.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzmk<String> zzbkc = zzmk.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzmk<String> zzbkd = zzmk.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzmk<Integer> zzbke = zzmk.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzmk<Integer> zzbkf = zzmk.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzmk<Integer> zzbkg = zzmk.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzmk<String> zzbkh = zzmk.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzmk<Integer> zzbki = zzmk.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzmk<Integer> zzbkj = zzmk.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzmk<Long> zzbkk = zzmk.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    public static final zzmk<Long> zzbkl = zzmk.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    public static final zzmk<Float> zzbkm = zzmk.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzmk<Float> zzbkn = zzmk.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    private static zzmk<Integer> zzbko = zzmk.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzmk<String> zzbkp = zzmk.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzmk<String> zzbkq = zzmk.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzmk<Boolean> zzbkr = zzmk.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbks = zzmk.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzmk<Long> zzbkt = zzmk.zza(1, "gads:position_watcher:throttle_ms", 200L);
    public static final zzmk<Boolean> zzbku = zzmk.zza(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final zzmk<Boolean> zzbkv = zzmk.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzmk<Long> zzbkw = zzmk.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final zzmk<Boolean> zzbkx = zzmk.zza(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbky = zzmk.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static zzmk<Boolean> zzbkz = zzmk.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static zzmk<Boolean> zzbla = zzmk.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static zzmk<Boolean> zzblb = zzmk.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static zzmk<Boolean> zzblc = zzmk.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbld = zzmk.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzble = zzmk.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    private static zzmk<String> zzblf = zzmk.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static zzmk<Long> zzblg = zzmk.zza(1, "gads:network:cache_prediction_duration_s", 300L);
    public static final zzmk<Long> zzblh = zzmk.zza(1, "gads:network:network_prediction_timeout_ms", 2000L);
    public static final zzmk<Boolean> zzbli = zzmk.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzmk<Boolean> zzblj = zzmk.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzmk<Boolean> zzblk = zzmk.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    public static final zzmk<Long> zzbll = zzmk.zza(0, "gads:resolve_future:default_timeout_ms", 30000L);
    public static final zzmk<Long> zzblm = zzmk.zza(0, "gads:ad_loader:timeout_ms", 60000L);
    public static final zzmk<Long> zzbln = zzmk.zza(0, "gads:rendering:timeout_ms", 60000L);
    public static final zzmk<Boolean> zzblo = zzmk.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzmk<Long> zzblp = zzmk.zza(1, "gads:gestures:task_timeout", 2000L);
    public static final zzmk<Boolean> zzblq = zzmk.zza(1, "gads:gestures:encrypt_size_limit:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzblr = zzmk.zza(1, "gads:gestures:orn_caching:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbls = zzmk.zza(1, "gads:gestures:oc:enabled", (Boolean) false);
    public static final zzmk<Integer> zzblt = zzmk.zza(1, "gads:gestures:ts", 1);
    public static final zzmk<Boolean> zzblu = zzmk.zza(1, "gads:gestures:td:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzblv = zzmk.zza(1, "gads:gestures:tdvs:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzblw = zzmk.zza(1, "gads:gestures:tuvs:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzblx = zzmk.zza(1, "gads:gestures:tvvs:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbly = zzmk.zza(1, "gads:gestures:vd:enabled", (Boolean) false);
    public static final zzmk<String> zzblz = zzmk.zza(1, "gads:gestures:pk", "");
    public static final zzmk<Boolean> zzbma = zzmk.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbmb = zzmk.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbmc = zzmk.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbmd = zzmk.zza(0, "gass:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbme = zzmk.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzmk<Boolean> zzbmf = zzmk.zza(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static zzmk<Boolean> zzbmg = zzmk.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static zzmk<Boolean> zzbmh = zzmk.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbmi = zzmk.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzmk<Boolean> zzbmj = zzmk.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    private static zzmk<String> zzbmk = zzmk.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static zzmk<String> zzbml = zzmk.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzmk<String> zzbmm = zzmk.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzmk<Long> zzbmn = zzmk.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzmk<Boolean> zzbmo = zzmk.zza(0, "gads:js_flags:mf", (Boolean) false);
    public static final zzmk<Boolean> zzbmp = zzmk.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    private static zzmk<String> zzbmq = zzmk.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzmk<String> zzbmr = zzmk.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static zzmk<String> zzbms = zzmk.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final zzmk<String> zzbmt = zzmk.zza(1, "gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final zzmk<Boolean> zzbmu = zzmk.zza(1, "gads:singleton_webview_native", (Boolean) false);
    public static final zzmk<Boolean> zzbmv = zzmk.zza(1, "gads:native_initialize_webview_request_time", (Boolean) false);
    private static zzmk<String> zzbmw = zzmk.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzmk<Boolean> zzbmx = zzmk.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzmk<Boolean> zzbmy = zzmk.zza(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final zzmk<Boolean> zzbmz = zzmk.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzmk<Integer> zzbna = zzmk.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzmk<String> zzbnb = zzmk.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzmk<Boolean> zzbnc = zzmk.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final zzmk<Boolean> zzbnd = zzmk.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzmk<Integer> zzbne = zzmk.zza(1, "gads:max_number_of_native_ads_allowed", 5);
    public static final zzmk<Boolean> zzbnf = zzmk.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final zzmk<Boolean> zzbng = zzmk.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzmk<Long> zzbnh = zzmk.zza(0, "gads:method_tracing:duration_ms", 30000L);
    public static final zzmk<Integer> zzbni = zzmk.zza(0, "gads:method_tracing:count", 5);
    public static final zzmk<Integer> zzbnj = zzmk.zza(0, "gads:method_tracing:filesize", 134217728);
    private static zzmk<Boolean> zzbnk = zzmk.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static zzmk<String> zzbnl = zzmk.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzmk<Long> zzbnm = zzmk.zza(1, "gads:auto_location_timeout", 2000L);
    private static zzmk<String> zzbnn = zzmk.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static zzmk<Long> zzbno = zzmk.zza(1, "gads:auto_location_interval", -1L);
    private static zzmk<String> zzbnp = zzmk.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzmk<Boolean> zzbnq = zzmk.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static zzmk<String> zzbnr = zzmk.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzmk<Long> zzbns = zzmk.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    private static zzmk<String> zzbnt = zzmk.zza(0, "gads:afs:csa:experiment_id");
    public static final zzmk<String> zzbnu = zzmk.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzmk<String> zzbnv = zzmk.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzmk<String> zzbnw = zzmk.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzmk<String> zzbnx = zzmk.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzmk<String> zzbny = zzmk.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzmk<Long> zzbnz = zzmk.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    private static zzmk<Boolean> zzboa = zzmk.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static zzmk<Boolean> zzbob = zzmk.zza(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static zzmk<Boolean> zzboc = zzmk.zza(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final zzmk<Long> zzbod = zzmk.zza(1, "gads:parental_controls:timeout", 2000L);
    private static zzmk<String> zzboe = zzmk.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static zzmk<Long> zzbof = zzmk.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    public static final zzmk<Boolean> zzbog = zzmk.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzmk<Boolean> zzboh = zzmk.zza(0, "gads:webview_cookie:enabled", (Boolean) true);
    private static zzmk<Integer> zzboi = zzmk.zza(1, "gads:cache:ad_request_timeout_millis", (int) ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static zzmk<Integer> zzboj = zzmk.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static zzmk<Long> zzbok = zzmk.zza(1, "gads:cache:javascript_timeout_millis", (long) ExoPlayerFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzmk<Boolean> zzbol = zzmk.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzmk<Boolean> zzbom = zzmk.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzmk<Boolean> zzbon = zzmk.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzmk<Long> zzboo = zzmk.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    private static zzmk<Boolean> zzbop = zzmk.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    private static zzmk<Boolean> zzboq = zzmk.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    private static zzmk<Long> zzbor = zzmk.zza(1, "gads:cache:connection_timeout", (long) ExoPlayerFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    private static zzmk<Long> zzbos = zzmk.zza(1, "gads:cache:read_only_connection_timeout", (long) ExoPlayerFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzmk<Boolean> zzbot = zzmk.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbou = zzmk.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzmk<Boolean> zzbov = zzmk.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzmk<Boolean> zzbow = zzmk.zza(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final zzmk<Boolean> zzbox = zzmk.zza(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final zzmk<String> zzboy = zzmk.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzmk<String> zzboz = zzmk.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzmk<String> zzbpa = zzmk.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzmk<String> zzbpb = zzmk.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzmk<Integer> zzbpc = zzmk.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzmk<Integer> zzbpd = zzmk.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzmk<Boolean> zzbpe = zzmk.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzmk<Boolean> zzbpf = zzmk.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzmk<Integer> zzbpg = zzmk.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzmk<Boolean> zzbph = zzmk.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    private static zzmk<Boolean> zzbpi = zzmk.zza(1, "gads:clearcut_abtest:enabled", (Boolean) false);
    public static final zzmk<Integer> zzbpj = zzmk.zza(1, "gads:clearcut_messageTime:ms", 60000);
    public static final zzmk<Boolean> zzbpk = zzmk.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final zzmk<Integer> zzbpl = zzmk.zza(1, "gad:http_redirect_max_count:times", 8);
    private static zzmk<Boolean> zzbpm = zzmk.zza(0, "gads:nonagon:red_button", (Boolean) false);
    private static zzmk<Boolean> zzbpn = zzmk.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static zzmk<String> zzbpo = zzmk.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static zzmk<Boolean> zzbpp = zzmk.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static zzmk<String> zzbpq = zzmk.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static zzmk<Boolean> zzbpr = zzmk.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static zzmk<String> zzbps = zzmk.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static zzmk<Boolean> zzbpt = zzmk.zza(1, "gads:nonagon:service:enabled", (Boolean) false);
    public static final zzmk<Long> zzbpu = zzmk.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    private static byte[] zzbpv;

    public static void initialize(Context context) {
        zzaiz.zza(new zzmv(context));
        int intValue = ((Integer) com.google.android.gms.ads.internal.zzbv.zzen().zzd(zzbko)).intValue();
        if (intValue <= 0 || zzbpv != null) {
            return;
        }
        zzbpv = new byte[intValue];
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        com.google.android.gms.ads.internal.zzbv.zzel();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        com.google.android.gms.ads.internal.zzbv.zzem().zza(edit, 1, jSONObject);
        com.google.android.gms.ads.internal.zzbv.zzel();
        edit.commit();
    }

    public static List<String> zzil() {
        return com.google.android.gms.ads.internal.zzbv.zzem().zzil();
    }

    public static List<String> zzim() {
        return com.google.android.gms.ads.internal.zzbv.zzem().zzim();
    }
}
